"""Seed the exercise database with 300+ exercises.

Run from the backend directory:
    python ../scripts/seed_exercises.py
"""
import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/backend")

import app.models  # noqa: F401 — registers all models with SQLAlchemy
from app.db.session import SessionLocal
from app.models.exercise import Exercise, ExerciseCategory, MuscleGroup

CATEGORIES = [
    {"id": 1, "name": "Chest", "name_tr": "Göğüs", "slug": "chest"},
    {"id": 2, "name": "Back", "name_tr": "Sırt", "slug": "back"},
    {"id": 3, "name": "Legs", "name_tr": "Bacaklar", "slug": "legs"},
    {"id": 4, "name": "Shoulders", "name_tr": "Omuzlar", "slug": "shoulders"},
    {"id": 5, "name": "Arms", "name_tr": "Kollar", "slug": "arms"},
    {"id": 6, "name": "Core", "name_tr": "Core", "slug": "core"},
]

MUSCLE_GROUPS = [
    {"id": 1, "name": "Chest", "name_tr": "Göğüs", "slug": "chest"},
    {"id": 2, "name": "Upper Back", "name_tr": "Üst Sırt", "slug": "upper-back"},
    {"id": 3, "name": "Lats", "name_tr": "Latissimus", "slug": "lats"},
    {"id": 4, "name": "Lower Back", "name_tr": "Bel", "slug": "lower-back"},
    {"id": 5, "name": "Quadriceps", "name_tr": "Kuadriseps", "slug": "quadriceps"},
    {"id": 6, "name": "Hamstrings", "name_tr": "Arka Bacak", "slug": "hamstrings"},
    {"id": 7, "name": "Glutes", "name_tr": "Kalça", "slug": "glutes"},
    {"id": 8, "name": "Calves", "name_tr": "Baldır", "slug": "calves"},
    {"id": 9, "name": "Front Delt", "name_tr": "Ön Omuz", "slug": "front-delt"},
    {"id": 10, "name": "Side Delt", "name_tr": "Yan Omuz", "slug": "side-delt"},
    {"id": 11, "name": "Rear Delt", "name_tr": "Arka Omuz", "slug": "rear-delt"},
    {"id": 12, "name": "Biceps", "name_tr": "Biseps", "slug": "biceps"},
    {"id": 13, "name": "Triceps", "name_tr": "Triseps", "slug": "triceps"},
    {"id": 14, "name": "Forearms", "name_tr": "Ön Kol", "slug": "forearms"},
    {"id": 15, "name": "Abs", "name_tr": "Karın", "slug": "abs"},
    {"id": 16, "name": "Obliques", "name_tr": "Yan Karın", "slug": "obliques"},
    {"id": 17, "name": "Traps", "name_tr": "Trapez", "slug": "traps"},
    {"id": 18, "name": "Hip Flexors", "name_tr": "Kalça Fleksörü", "slug": "hip-flexors"},
]

# (name, name_tr, category_id, primary_muscle_id, secondary_muscles_list, equipment, difficulty)
EXERCISES = [
    # ── CHEST (cat 1) ──────────────────────────────────────────────────────────
    ("Bench Press", "Baskı (Düz)", 1, 1, ["Triceps", "Front Delt"], "barbell", "intermediate"),
    ("Incline Bench Press", "Baskı (Eğimli)", 1, 1, ["Triceps", "Front Delt"], "barbell", "intermediate"),
    ("Decline Bench Press", "Baskı (Negatif Eğimli)", 1, 1, ["Triceps"], "barbell", "intermediate"),
    ("Dumbbell Bench Press", "Dumbbell Baskı (Düz)", 1, 1, ["Triceps", "Front Delt"], "dumbbell", "beginner"),
    ("Incline Dumbbell Press", "Dumbbell Baskı (Eğimli)", 1, 1, ["Triceps", "Front Delt"], "dumbbell", "beginner"),
    ("Decline Dumbbell Press", "Dumbbell Baskı (Negatif)", 1, 1, ["Triceps"], "dumbbell", "beginner"),
    ("Push-Up", "Şınav", 1, 1, ["Triceps", "Front Delt"], "bodyweight", "beginner"),
    ("Wide Push-Up", "Geniş Tutuş Şınav", 1, 1, ["Triceps"], "bodyweight", "beginner"),
    ("Diamond Push-Up", "Elmas Şınav", 1, 13, ["Chest"], "bodyweight", "intermediate"),
    ("Cable Crossover", "Kablo Göğüs", 1, 1, ["Front Delt"], "cable", "intermediate"),
    ("Pec Deck Fly", "Kelebek Makinesi", 1, 1, [], "machine", "beginner"),
    ("Dumbbell Fly", "Dumbbell Açılımı (Düz)", 1, 1, ["Front Delt"], "dumbbell", "beginner"),
    ("Incline Dumbbell Fly", "Dumbbell Açılımı (Eğimli)", 1, 1, ["Front Delt"], "dumbbell", "intermediate"),
    ("Decline Dumbbell Fly", "Dumbbell Açılımı (Negatif)", 1, 1, [], "dumbbell", "intermediate"),
    ("Chest Press Machine", "Göğüs Baskı Makinesi", 1, 1, ["Triceps"], "machine", "beginner"),
    ("Smith Machine Bench Press", "Smith Makinesi Baskı", 1, 1, ["Triceps", "Front Delt"], "machine", "intermediate"),
    ("Close-Grip Bench Press", "Dar Tutuş Baskı", 1, 13, ["Chest"], "barbell", "intermediate"),
    ("Floor Press", "Zemin Baskı", 1, 1, ["Triceps"], "barbell", "intermediate"),
    ("Dips (Chest)", "Dips (Göğüs)", 1, 1, ["Triceps", "Front Delt"], "bodyweight", "intermediate"),
    ("Cable Fly (Low to High)", "Kablo Açılımı (Aşağıdan Yukarı)", 1, 1, [], "cable", "intermediate"),
    ("Cable Fly (High to Low)", "Kablo Açılımı (Yukarıdan Aşağı)", 1, 1, [], "cable", "intermediate"),
    ("Cable Fly (Mid)", "Kablo Açılımı (Orta)", 1, 1, [], "cable", "intermediate"),
    ("Svend Press", "Svend Baskı", 1, 1, [], "other", "beginner"),
    ("Landmine Press", "Landmine Baskı", 1, 1, ["Front Delt", "Triceps"], "barbell", "intermediate"),
    ("Push-Up with Feet Elevated", "Ayaklar Yüksek Şınav", 1, 1, ["Front Delt"], "bodyweight", "intermediate"),
    ("Archer Push-Up", "Okçu Şınavı", 1, 1, ["Triceps"], "bodyweight", "advanced"),
    ("Banded Push-Up", "Direnç Bantlı Şınav", 1, 1, ["Triceps"], "band", "intermediate"),
    ("TRX Push-Up", "TRX Şınavı", 1, 1, ["Triceps", "Abs"], "other", "intermediate"),
    ("Single-Arm Dumbbell Press", "Tek Kol Dumbbell Baskı", 1, 1, ["Triceps"], "dumbbell", "intermediate"),
    ("Squeeze Press", "Sıkıştırmalı Baskı", 1, 1, [], "dumbbell", "intermediate"),
    ("Resistance Band Chest Press", "Bantlı Göğüs Baskı", 1, 1, ["Triceps"], "band", "beginner"),
    ("Resistance Band Fly", "Bantlı Göğüs Açılımı", 1, 1, [], "band", "beginner"),
    ("Hex Press", "Hex Baskı", 1, 1, ["Triceps"], "dumbbell", "intermediate"),
    ("Plate Press", "Plaka Baskı", 1, 1, [], "other", "beginner"),
    ("Neck Press", "Boyun Baskı", 1, 1, ["Triceps"], "barbell", "advanced"),
    ("Incline Smith Machine Press", "Eğimli Smith Baskı", 1, 1, ["Triceps", "Front Delt"], "machine", "intermediate"),
    ("Decline Smith Machine Press", "Negatif Smith Baskı", 1, 1, ["Triceps"], "machine", "intermediate"),
    ("Single-Arm Cable Press", "Tek Kol Kablo Baskı", 1, 1, ["Triceps"], "cable", "intermediate"),
    ("Explosive Push-Up", "Patlayıcı Şınav", 1, 1, ["Triceps"], "bodyweight", "advanced"),
    ("Guillotine Press", "Giyotin Baskı", 1, 1, ["Front Delt"], "barbell", "advanced"),

    # ── BACK (cat 2) ──────────────────────────────────────────────────────────
    ("Pull-Up", "Barfiks", 2, 3, ["Biceps", "Upper Back"], "bodyweight", "intermediate"),
    ("Chin-Up", "Ters Barfiks", 2, 3, ["Biceps"], "bodyweight", "intermediate"),
    ("Lat Pulldown", "Lat Çekişi", 2, 3, ["Biceps", "Upper Back"], "cable", "beginner"),
    ("Seated Cable Row", "Oturarak Kablo Çekiş", 2, 2, ["Biceps", "Lats"], "cable", "beginner"),
    ("Bent-Over Barbell Row", "Öne Eğik Barbell Çekiş", 2, 2, ["Biceps", "Lats", "Lower Back"], "barbell", "intermediate"),
    ("T-Bar Row", "T-Bar Çekiş", 2, 2, ["Biceps", "Lats"], "barbell", "intermediate"),
    ("Single-Arm Dumbbell Row", "Tek Kol Dumbbell Çekiş", 2, 2, ["Biceps", "Lats"], "dumbbell", "beginner"),
    ("Deadlift", "Deadlift", 2, 4, ["Glutes", "Hamstrings", "Upper Back", "Traps"], "barbell", "advanced"),
    ("Romanian Deadlift", "Romen Deadlift", 2, 6, ["Glutes", "Lower Back"], "barbell", "intermediate"),
    ("Sumo Deadlift", "Sumo Deadlift", 2, 4, ["Glutes", "Hamstrings", "Quadriceps"], "barbell", "advanced"),
    ("Good Morning", "Good Morning", 2, 4, ["Glutes", "Hamstrings"], "barbell", "intermediate"),
    ("Back Extension", "Sırt Uzatma", 2, 4, ["Glutes"], "machine", "beginner"),
    ("Hyperextension", "Hiperekstansiyon", 2, 4, ["Glutes"], "bodyweight", "beginner"),
    ("Rack Pull", "Rack Çekişi", 2, 2, ["Traps", "Lower Back"], "barbell", "intermediate"),
    ("Meadows Row", "Meadows Çekişi", 2, 3, ["Biceps", "Upper Back"], "barbell", "intermediate"),
    ("Pendlay Row", "Pendlay Çekişi", 2, 2, ["Biceps", "Lats"], "barbell", "advanced"),
    ("Chest-Supported Row", "Göğüs Destekli Çekiş", 2, 2, ["Biceps", "Rear Delt"], "dumbbell", "beginner"),
    ("Wide-Grip Pull-Up", "Geniş Tutuş Barfiks", 2, 3, ["Upper Back"], "bodyweight", "intermediate"),
    ("Neutral-Grip Pull-Up", "Nötr Tutuş Barfiks", 2, 3, ["Biceps"], "bodyweight", "intermediate"),
    ("Assisted Pull-Up", "Yardımlı Barfiks", 2, 3, ["Biceps"], "machine", "beginner"),
    ("Inverted Row", "Yatay Barfiks", 2, 2, ["Biceps", "Rear Delt"], "bodyweight", "beginner"),
    ("Cable Row (Wide Grip)", "Geniş Tutuş Kablo Çekiş", 2, 2, ["Rear Delt", "Biceps"], "cable", "beginner"),
    ("Straight-Arm Pulldown", "Düz Kol Lat Çekişi", 2, 3, [], "cable", "intermediate"),
    ("Dumbbell Pullover", "Dumbbell Pullover", 2, 3, ["Chest"], "dumbbell", "intermediate"),
    ("Cable Pullover", "Kablo Pullover", 2, 3, [], "cable", "intermediate"),
    ("Close-Grip Lat Pulldown", "Dar Tutuş Lat Çekişi", 2, 3, ["Biceps"], "cable", "beginner"),
    ("Face Pull", "Face Pull", 2, 11, ["Upper Back", "Traps"], "cable", "beginner"),
    ("Barbell Shrug", "Barbell Omuz Silkme", 2, 17, [], "barbell", "beginner"),
    ("Dumbbell Shrug", "Dumbbell Omuz Silkme", 2, 17, [], "dumbbell", "beginner"),
    ("Cable Shrug", "Kablo Omuz Silkme", 2, 17, [], "cable", "beginner"),
    ("Snatch-Grip Deadlift", "Snatch Tutuş Deadlift", 2, 4, ["Upper Back", "Traps"], "barbell", "advanced"),
    ("Trap Bar Deadlift", "Trap Bar Deadlift", 2, 4, ["Quadriceps", "Glutes", "Upper Back"], "other", "intermediate"),
    ("Stiff-Leg Deadlift", "Düz Bacak Deadlift", 2, 6, ["Glutes", "Lower Back"], "barbell", "intermediate"),
    ("Single-Leg Deadlift", "Tek Bacak Deadlift", 2, 6, ["Glutes"], "dumbbell", "intermediate"),
    ("Resistance Band Row", "Bantlı Sırt Çekişi", 2, 2, ["Biceps"], "band", "beginner"),
    ("TRX Row", "TRX Çekişi", 2, 2, ["Biceps", "Rear Delt"], "other", "beginner"),
    ("Kroc Row", "Kroc Çekişi", 2, 3, ["Biceps", "Traps"], "dumbbell", "advanced"),
    ("Reverse Grip Barbell Row", "Ters Tutuş Barbell Çekiş", 2, 3, ["Biceps"], "barbell", "intermediate"),
    ("Block Pull", "Blok Çekiş", 2, 2, ["Traps", "Lower Back"], "barbell", "advanced"),
    ("Jefferson Deadlift", "Jefferson Deadlift", 2, 4, ["Quadriceps", "Glutes"], "barbell", "advanced"),
    ("Dumbbell Row (Chest-Supported)", "Yatarak Dumbbell Çekiş", 2, 2, ["Rear Delt", "Biceps"], "dumbbell", "beginner"),
    ("Seated Good Morning", "Oturarak Good Morning", 2, 4, ["Glutes", "Hamstrings"], "barbell", "intermediate"),
    ("Resistance Band Pull-Apart", "Bant Açılımı", 2, 11, ["Upper Back"], "band", "beginner"),
    ("Hammer Strength Row", "Hammer Strength Çekiş", 2, 2, ["Biceps", "Lats"], "machine", "beginner"),
    ("Smith Machine Row", "Smith Makinesi Çekiş", 2, 2, ["Biceps", "Lats"], "machine", "intermediate"),
    ("Single-Arm Lat Pulldown", "Tek Kol Lat Çekişi", 2, 3, ["Biceps"], "cable", "beginner"),
    ("Wide-Grip Seated Row", "Geniş Tutuş Kablo Çekiş (Oturarak)", 2, 2, ["Rear Delt"], "cable", "beginner"),
    ("Seated Cable Pullover", "Oturarak Kablo Pullover", 2, 3, [], "cable", "intermediate"),
    ("Ring Pull-Up", "Halka Barfiks", 2, 3, ["Biceps", "Abs"], "other", "advanced"),
    ("Cable Row (Narrow Grip)", "Dar Tutuş Kablo Çekiş", 2, 2, ["Biceps", "Lats"], "cable", "beginner"),

    # ── LEGS (cat 3) ──────────────────────────────────────────────────────────
    ("Squat", "Squat", 3, 5, ["Glutes", "Hamstrings", "Lower Back"], "barbell", "intermediate"),
    ("Front Squat", "Ön Squat", 3, 5, ["Glutes", "Upper Back"], "barbell", "advanced"),
    ("Goblet Squat", "Goblet Squat", 3, 5, ["Glutes", "Abs"], "dumbbell", "beginner"),
    ("Leg Press", "Bacak Baskı", 3, 5, ["Glutes", "Hamstrings"], "machine", "beginner"),
    ("Leg Curl (Lying)", "Bacak Bükme (Yatar)", 3, 6, [], "machine", "beginner"),
    ("Leg Curl (Seated)", "Bacak Bükme (Oturur)", 3, 6, [], "machine", "beginner"),
    ("Leg Extension", "Bacak Uzatma", 3, 5, [], "machine", "beginner"),
    ("Lunges", "Akciğer Hareketi", 3, 5, ["Glutes", "Hamstrings"], "dumbbell", "beginner"),
    ("Reverse Lunges", "Ters Akciğer", 3, 5, ["Glutes"], "dumbbell", "beginner"),
    ("Walking Lunges", "Yürüyüş Akciğer", 3, 5, ["Glutes", "Hamstrings"], "dumbbell", "intermediate"),
    ("Bulgarian Split Squat", "Bulgar Squat", 3, 5, ["Glutes", "Hamstrings"], "dumbbell", "intermediate"),
    ("Box Squat", "Kutu Squat", 3, 5, ["Glutes"], "barbell", "intermediate"),
    ("Hack Squat", "Hack Squat", 3, 5, ["Glutes"], "machine", "intermediate"),
    ("Sumo Squat", "Sumo Squat", 3, 7, ["Quadriceps", "Hamstrings"], "barbell", "intermediate"),
    ("Calf Raise (Standing)", "Baldır Baskı (Ayakta)", 3, 8, [], "machine", "beginner"),
    ("Calf Raise (Seated)", "Baldır Baskı (Oturarak)", 3, 8, [], "machine", "beginner"),
    ("Donkey Calf Raise", "Eşek Baldır Baskı", 3, 8, [], "machine", "intermediate"),
    ("Smith Machine Squat", "Smith Makinesi Squat", 3, 5, ["Glutes"], "machine", "beginner"),
    ("Leg Press Calf Raise", "Bacak Presi Baldır Baskı", 3, 8, [], "machine", "beginner"),
    ("Hip Thrust", "Kalça İtişi", 3, 7, ["Hamstrings"], "barbell", "intermediate"),
    ("Glute Bridge", "Kalça Köprüsü", 3, 7, ["Hamstrings"], "bodyweight", "beginner"),
    ("Single-Leg Hip Thrust", "Tek Bacak Kalça İtişi", 3, 7, ["Hamstrings"], "bodyweight", "intermediate"),
    ("Cable Kickback", "Kablo Tekme", 3, 7, [], "cable", "beginner"),
    ("Abductor Machine", "Abduktor Makinesi", 3, 7, [], "machine", "beginner"),
    ("Adductor Machine", "Adduktor Makinesi", 3, 7, [], "machine", "beginner"),
    ("Step-Up", "Basamak Çıkışı", 3, 5, ["Glutes"], "dumbbell", "beginner"),
    ("Box Jump", "Kutu Atlama", 3, 5, ["Glutes", "Calves"], "bodyweight", "intermediate"),
    ("Lateral Lunge", "Yan Akciğer", 3, 5, ["Glutes"], "bodyweight", "beginner"),
    ("Curtsy Lunge", "Reverans Akciğer", 3, 7, ["Quadriceps"], "dumbbell", "intermediate"),
    ("Sissy Squat", "Sissy Squat", 3, 5, [], "bodyweight", "advanced"),
    ("Nordic Curl", "Nordic Curl", 3, 6, ["Glutes"], "bodyweight", "advanced"),
    ("Glute-Ham Raise", "Kalça-Arka Bacak Kaldırma", 3, 6, ["Glutes"], "machine", "advanced"),
    ("Single-Leg Press", "Tek Bacak Presi", 3, 5, ["Glutes"], "machine", "intermediate"),
    ("Single-Leg Curl", "Tek Bacak Bükme", 3, 6, [], "machine", "intermediate"),
    ("Single-Leg Extension", "Tek Bacak Uzatma", 3, 5, [], "machine", "intermediate"),
    ("Split Squat", "Yarılmış Squat", 3, 5, ["Glutes"], "bodyweight", "beginner"),
    ("Pistol Squat", "Tek Bacak Squat", 3, 5, ["Glutes"], "bodyweight", "advanced"),
    ("Wall Sit", "Duvar Oturması", 3, 5, [], "bodyweight", "beginner"),
    ("Jump Squat", "Sıçrama Squat", 3, 5, ["Calves"], "bodyweight", "intermediate"),
    ("Resistance Band Squat", "Bantlı Squat", 3, 5, ["Glutes"], "band", "beginner"),
    ("Resistance Band Hip Thrust", "Bantlı Kalça İtişi", 3, 7, [], "band", "beginner"),
    ("Resistance Band Kickback", "Bantlı Tekme", 3, 7, [], "band", "beginner"),
    ("Sled Push", "Kızak İtişi", 3, 5, ["Glutes", "Calves"], "other", "intermediate"),
    ("Farmer's Walk", "Çiftçi Yürüyüşü", 3, 5, ["Traps", "Forearms"], "dumbbell", "intermediate"),
    ("Leg Abduction (Cable)", "Bacak Açılımı (Kablo)", 3, 7, [], "cable", "beginner"),
    ("Leg Adduction (Cable)", "Bacak Kapanımı (Kablo)", 3, 7, [], "cable", "beginner"),
    ("Zercher Squat", "Zercher Squat", 3, 5, ["Glutes", "Upper Back"], "barbell", "advanced"),
    ("Safety Bar Squat", "Safety Bar Squat", 3, 5, ["Glutes", "Upper Back"], "barbell", "intermediate"),
    ("Paused Squat", "Duraklamalı Squat", 3, 5, ["Glutes"], "barbell", "advanced"),
    ("Broad Jump", "Uzun Atlama", 3, 5, ["Glutes", "Calves"], "bodyweight", "intermediate"),
    ("Resistance Band Abduction", "Bantlı Bacak Açılımı", 3, 7, [], "band", "beginner"),
    ("Trap Bar Deadlift (Legs)", "Trap Bar Deadlift (Bacak)", 3, 5, ["Glutes", "Hamstrings"], "other", "intermediate"),
    ("Stiff-Leg Deadlift (Legs)", "Düz Bacak Deadlift (Bacak)", 3, 6, ["Glutes"], "barbell", "intermediate"),
    ("Reverse Hyperextension", "Ters Hiperekstansiyon", 3, 7, ["Hamstrings", "Lower Back"], "machine", "intermediate"),
    ("Good Morning (Legs)", "Good Morning (Bacak)", 3, 6, ["Glutes", "Lower Back"], "barbell", "intermediate"),
    ("Calf Raise (Single-Leg)", "Tek Bacak Baldır Baskı", 3, 8, [], "bodyweight", "intermediate"),
    ("Romanian Deadlift (Dumbbell)", "Romen Deadlift (Dumbbell)", 3, 6, ["Glutes"], "dumbbell", "intermediate"),
    ("Hip Abductor Raise", "Kalça Abduktör Kaldırma", 3, 7, [], "bodyweight", "beginner"),
    ("Sumo Deadlift High Pull", "Sumo Deadlift Yüksek Çekiş", 3, 5, ["Glutes", "Traps"], "barbell", "intermediate"),
    ("Power Clean", "Power Clean", 3, 5, ["Glutes", "Upper Back", "Traps"], "barbell", "advanced"),

    # ── SHOULDERS (cat 4) ─────────────────────────────────────────────────────
    ("Overhead Press", "Baş Üstü Baskı", 4, 9, ["Triceps", "Upper Back"], "barbell", "intermediate"),
    ("Seated Overhead Press", "Oturarak Baş Üstü Baskı", 4, 9, ["Triceps"], "barbell", "intermediate"),
    ("Dumbbell Shoulder Press", "Dumbbell Omuz Baskı", 4, 9, ["Triceps", "Side Delt"], "dumbbell", "beginner"),
    ("Arnold Press", "Arnold Baskı", 4, 9, ["Side Delt", "Front Delt"], "dumbbell", "intermediate"),
    ("Push Press", "İtiş Baskı", 4, 9, ["Triceps", "Quadriceps"], "barbell", "intermediate"),
    ("Behind-the-Neck Press", "Boyun Arkası Baskı", 4, 9, ["Triceps", "Side Delt"], "barbell", "advanced"),
    ("Smith Machine Shoulder Press", "Smith Omuz Baskı", 4, 9, ["Triceps"], "machine", "beginner"),
    ("Cable Lateral Raise", "Kablo Yan Kaldırma", 4, 10, [], "cable", "beginner"),
    ("Dumbbell Lateral Raise", "Dumbbell Yan Kaldırma", 4, 10, [], "dumbbell", "beginner"),
    ("Front Raise (Barbell)", "Ön Kaldırma (Barbell)", 4, 9, [], "barbell", "beginner"),
    ("Front Raise (Dumbbell)", "Ön Kaldırma (Dumbbell)", 4, 9, [], "dumbbell", "beginner"),
    ("Front Raise (Cable)", "Ön Kaldırma (Kablo)", 4, 9, [], "cable", "beginner"),
    ("Rear Delt Fly", "Arka Omuz Açılımı", 4, 11, [], "dumbbell", "beginner"),
    ("Rear Delt Row", "Arka Omuz Çekişi", 4, 11, ["Upper Back"], "cable", "beginner"),
    ("Reverse Pec Deck", "Ters Kelebek", 4, 11, ["Upper Back"], "machine", "beginner"),
    ("Cable Rear Delt Fly", "Kablo Arka Omuz Açılımı", 4, 11, [], "cable", "beginner"),
    ("Upright Row (Barbell)", "Dik Çekiş (Barbell)", 4, 10, ["Biceps", "Traps"], "barbell", "intermediate"),
    ("Upright Row (Dumbbell)", "Dik Çekiş (Dumbbell)", 4, 10, ["Biceps", "Traps"], "dumbbell", "beginner"),
    ("Upright Row (Cable)", "Dik Çekiş (Kablo)", 4, 10, ["Biceps", "Traps"], "cable", "beginner"),
    ("Face Pull", "Face Pull (Omuz)", 4, 11, ["Upper Back"], "cable", "beginner"),
    ("Band Pull-Apart", "Bant Açılımı (Omuz)", 4, 11, ["Upper Back"], "band", "beginner"),
    ("External Rotation (Cable)", "Dış Rotasyon (Kablo)", 4, 11, [], "cable", "beginner"),
    ("Internal Rotation (Cable)", "İç Rotasyon (Kablo)", 4, 9, [], "cable", "beginner"),
    ("Landmine Press (Single-Arm)", "Landmine Tek Kol Baskı", 4, 9, ["Triceps"], "barbell", "intermediate"),
    ("Plate Raise", "Plaka Kaldırma", 4, 9, [], "other", "beginner"),
    ("Prone Y-Raise", "Yüzüstü Y Kaldırma", 4, 11, ["Upper Back"], "dumbbell", "beginner"),
    ("Prone T-Raise", "Yüzüstü T Kaldırma", 4, 11, ["Upper Back"], "dumbbell", "beginner"),
    ("Prone W-Raise", "Yüzüstü W Kaldırma", 4, 11, ["Upper Back"], "dumbbell", "beginner"),
    ("Handstand Push-Up", "El Duruşu Şınavı", 4, 9, ["Triceps"], "bodyweight", "advanced"),
    ("Pike Push-Up", "Pike Şınavı", 4, 9, ["Triceps"], "bodyweight", "intermediate"),
    ("Bradford Press", "Bradford Baskı", 4, 9, ["Side Delt", "Front Delt"], "barbell", "advanced"),
    ("Cuban Press", "Küba Baskı", 4, 11, ["Side Delt"], "dumbbell", "intermediate"),
    ("Z-Press", "Z Baskı", 4, 9, ["Abs", "Triceps"], "barbell", "advanced"),
    ("Seated Cable Lateral Raise", "Oturarak Kablo Yan Kaldırma", 4, 10, [], "cable", "intermediate"),
    ("Machine Shoulder Press", "Makine Omuz Baskı", 4, 9, ["Triceps"], "machine", "beginner"),
    ("Machine Lateral Raise", "Makine Yan Kaldırma", 4, 10, [], "machine", "beginner"),
    ("Kettlebell Press", "Kettlebell Baskı", 4, 9, ["Triceps"], "other", "intermediate"),
    ("Dumbbell Y-Raise", "Dumbbell Y Kaldırma", 4, 11, ["Upper Back"], "dumbbell", "beginner"),
    ("Dumbbell T-Raise", "Dumbbell T Kaldırma", 4, 11, [], "dumbbell", "beginner"),
    ("Resistance Band Lateral Raise", "Bantlı Yan Kaldırma", 4, 10, [], "band", "beginner"),
    ("Resistance Band Front Raise", "Bantlı Ön Kaldırma", 4, 9, [], "band", "beginner"),
    ("Resistance Band Rear Delt Fly", "Bantlı Arka Omuz Açılımı", 4, 11, [], "band", "beginner"),
    ("Landmine Lateral Raise", "Landmine Yan Kaldırma", 4, 10, [], "barbell", "intermediate"),
    ("Dumbbell Rear Delt Row", "Dumbbell Arka Omuz Çekiş", 4, 11, ["Upper Back"], "dumbbell", "beginner"),
    ("Kettlebell High Pull", "Kettlebell Yüksek Çekiş", 4, 10, ["Traps", "Biceps"], "other", "intermediate"),

    # ── ARMS (cat 5) ──────────────────────────────────────────────────────────
    # Biceps
    ("Barbell Curl", "Barbell Kıvrımı", 5, 12, ["Forearms"], "barbell", "beginner"),
    ("EZ-Bar Curl", "EZ-Bar Kıvrımı", 5, 12, ["Forearms"], "barbell", "beginner"),
    ("Dumbbell Curl", "Dumbbell Kıvrımı", 5, 12, ["Forearms"], "dumbbell", "beginner"),
    ("Hammer Curl", "Çekiç Kıvrım", 5, 12, ["Forearms"], "dumbbell", "beginner"),
    ("Concentration Curl", "Konsantrasyon Kıvrımı", 5, 12, [], "dumbbell", "beginner"),
    ("Preacher Curl (Barbell)", "Preacher Curl (Barbell)", 5, 12, [], "barbell", "beginner"),
    ("Preacher Curl (Dumbbell)", "Preacher Curl (Dumbbell)", 5, 12, [], "dumbbell", "beginner"),
    ("Spider Curl", "Örümcek Kıvrımı", 5, 12, [], "dumbbell", "intermediate"),
    ("Cable Curl (Straight Bar)", "Kablo Curl (Düz Bar)", 5, 12, ["Forearms"], "cable", "beginner"),
    ("Cable Curl (Rope)", "Kablo Curl (İp)", 5, 12, ["Forearms"], "cable", "beginner"),
    ("Incline Dumbbell Curl", "Eğimli Dumbbell Curl", 5, 12, [], "dumbbell", "intermediate"),
    ("Reverse Curl", "Ters Kıvrım", 5, 14, ["Biceps"], "barbell", "beginner"),
    ("Zottman Curl", "Zottman Curl", 5, 12, ["Forearms"], "dumbbell", "intermediate"),
    ("Cross-Body Curl", "Çapraz Curl", 5, 12, [], "dumbbell", "beginner"),
    ("21s", "21'ler", 5, 12, [], "barbell", "intermediate"),
    ("Single-Arm Cable Curl", "Tek Kol Kablo Curl", 5, 12, [], "cable", "beginner"),
    ("Machine Curl", "Makine Curl", 5, 12, [], "machine", "beginner"),
    ("Resistance Band Curl", "Bantlı Curl", 5, 12, ["Forearms"], "band", "beginner"),
    ("High Cable Curl", "Yüksek Kablo Curl", 5, 12, [], "cable", "intermediate"),
    ("Drag Curl", "Sürükleme Curl", 5, 12, [], "barbell", "intermediate"),
    # Triceps
    ("Skull Crusher (EZ-Bar)", "Kafa Ezici (EZ-Bar)", 5, 13, [], "barbell", "intermediate"),
    ("Skull Crusher (Barbell)", "Kafa Ezici (Barbell)", 5, 13, [], "barbell", "intermediate"),
    ("Tricep Pushdown (Rope)", "Triseps İniş (İp)", 5, 13, [], "cable", "beginner"),
    ("Tricep Pushdown (Bar)", "Triseps İniş (Bar)", 5, 13, [], "cable", "beginner"),
    ("Overhead Tricep Extension (Dumbbell)", "Baş Üstü Triseps (Dumbbell)", 5, 13, [], "dumbbell", "beginner"),
    ("Overhead Tricep Extension (Cable)", "Baş Üstü Triseps (Kablo)", 5, 13, [], "cable", "beginner"),
    ("Overhead Tricep Extension (EZ-Bar)", "Baş Üstü Triseps (EZ-Bar)", 5, 13, [], "barbell", "intermediate"),
    ("Dips (Triceps)", "Dips (Triseps)", 5, 13, ["Chest", "Front Delt"], "bodyweight", "intermediate"),
    ("Kickback (Dumbbell)", "Geri Tekme (Dumbbell)", 5, 13, [], "dumbbell", "beginner"),
    ("Kickback (Cable)", "Geri Tekme (Kablo)", 5, 13, [], "cable", "beginner"),
    ("JM Press", "JM Baskı", 5, 13, [], "barbell", "advanced"),
    ("Tate Press", "Tate Baskı", 5, 13, [], "dumbbell", "intermediate"),
    ("Rolling Tricep Extension", "Yuvarlanma Triseps", 5, 13, [], "dumbbell", "intermediate"),
    ("Single-Arm Cable Extension", "Tek Kol Kablo Triseps", 5, 13, [], "cable", "beginner"),
    ("Single-Arm Overhead Extension", "Tek Kol Baş Üstü Triseps", 5, 13, [], "dumbbell", "beginner"),
    ("Machine Tricep Extension", "Makine Triseps", 5, 13, [], "machine", "beginner"),
    ("Resistance Band Pushdown", "Bantlı Triseps İniş", 5, 13, [], "band", "beginner"),
    ("French Press", "Fransız Baskı", 5, 13, [], "barbell", "intermediate"),
    ("Close-Grip Push-Up", "Dar Tutuş Şınav", 5, 13, ["Chest"], "bodyweight", "beginner"),
    ("Board Press", "Board Baskı", 5, 13, ["Chest"], "barbell", "advanced"),
    # Forearms
    ("Wrist Curl", "Bilek Kıvrımı", 5, 14, [], "barbell", "beginner"),
    ("Reverse Wrist Curl", "Ters Bilek Kıvrımı", 5, 14, [], "barbell", "beginner"),
    ("Wrist Roller", "Bilek Rulosu", 5, 14, [], "other", "beginner"),
    ("Dead Hang", "Ölü Asılma", 5, 14, ["Lats"], "bodyweight", "beginner"),
    ("Plate Pinch", "Plaka Sıkma", 5, 14, [], "other", "beginner"),
    ("Towel Pull-Up", "Havlu Barfiks", 5, 14, ["Biceps", "Lats"], "other", "advanced"),
    ("Thick Bar Curl", "Kalın Bar Curl", 5, 14, ["Biceps"], "barbell", "intermediate"),
    ("Farmer's Walk (Grip)", "Çiftçi Yürüyüşü (Tutuş)", 5, 14, ["Traps"], "dumbbell", "beginner"),
    ("EZ-Bar Reverse Curl", "EZ-Bar Ters Curl", 5, 14, ["Biceps"], "barbell", "beginner"),
    ("Cable Reverse Curl", "Kablo Ters Curl", 5, 14, ["Biceps"], "cable", "beginner"),

    # ── CORE (cat 6) ──────────────────────────────────────────────────────────
    # Abs
    ("Crunch", "Karın Kası", 6, 15, [], "bodyweight", "beginner"),
    ("Bicycle Crunch", "Bisiklet Hareketi", 6, 15, ["Obliques"], "bodyweight", "beginner"),
    ("Reverse Crunch", "Ters Karın", 6, 15, ["Hip Flexors"], "bodyweight", "beginner"),
    ("Hanging Leg Raise", "Asılı Bacak Kaldırma", 6, 15, ["Hip Flexors"], "bodyweight", "intermediate"),
    ("Lying Leg Raise", "Yatar Bacak Kaldırma", 6, 15, ["Hip Flexors"], "bodyweight", "beginner"),
    ("Plank", "Tahta", 6, 15, ["Obliques", "Lower Back"], "bodyweight", "beginner"),
    ("Side Plank", "Yan Tahta", 6, 16, ["Abs"], "bodyweight", "beginner"),
    ("Dragon Flag", "Ejderha Bayrağı", 6, 15, ["Hip Flexors"], "bodyweight", "advanced"),
    ("Ab Wheel Rollout", "Karın Tekerleği", 6, 15, ["Lower Back"], "other", "intermediate"),
    ("Cable Crunch", "Kablo Karın", 6, 15, [], "cable", "beginner"),
    ("Machine Crunch", "Makine Karın", 6, 15, [], "machine", "beginner"),
    ("Decline Crunch", "Eğimli Karın", 6, 15, [], "bodyweight", "intermediate"),
    ("V-Up", "V Hareketi", 6, 15, ["Hip Flexors"], "bodyweight", "intermediate"),
    ("Hollow Body Hold", "İçi Boş Vücut", 6, 15, [], "bodyweight", "intermediate"),
    ("Dead Bug", "Ölü Böcek", 6, 15, ["Lower Back"], "bodyweight", "beginner"),
    ("Russian Twist", "Rus Dönüşü", 6, 16, ["Abs"], "bodyweight", "beginner"),
    ("Windshield Wipers", "Silecek Hareketi", 6, 16, ["Abs"], "bodyweight", "advanced"),
    ("Toe Touch", "Parmak Ucu Dokunma", 6, 15, [], "bodyweight", "beginner"),
    ("Sit-Up", "Mekik", 6, 15, ["Hip Flexors"], "bodyweight", "beginner"),
    ("Decline Sit-Up", "Eğimli Mekik", 6, 15, ["Hip Flexors"], "bodyweight", "intermediate"),
    ("Cable Crunch (High to Low)", "Kablo Karın (Yukarıdan)", 6, 15, [], "cable", "beginner"),
    ("Swiss Ball Crunch", "Top Karın Hareketi", 6, 15, [], "other", "beginner"),
    ("Tuck Crunch", "Dizli Karın", 6, 15, [], "bodyweight", "beginner"),
    ("L-Sit", "L Oturma", 6, 15, ["Hip Flexors", "Triceps"], "bodyweight", "advanced"),
    ("Toes-to-Bar", "Ayak Ucu Bar", 6, 15, ["Hip Flexors", "Lats"], "bodyweight", "advanced"),
    ("Knee-to-Chest", "Diz Göğüse", 6, 15, ["Hip Flexors"], "bodyweight", "beginner"),
    ("Flutter Kicks", "Çırpma Tekmeleri", 6, 15, ["Hip Flexors"], "bodyweight", "beginner"),
    ("Scissor Kicks", "Makas Tekmeleri", 6, 15, ["Hip Flexors"], "bodyweight", "beginner"),
    # Obliques
    ("Side Crunch", "Yan Karın", 6, 16, ["Abs"], "bodyweight", "beginner"),
    ("Oblique Crunch", "Yan Karın Kası", 6, 16, [], "bodyweight", "beginner"),
    ("Woodchop (Cable)", "Odun Kesme (Kablo)", 6, 16, ["Abs"], "cable", "intermediate"),
    ("Pallof Press", "Pallof Baskı", 6, 16, ["Abs"], "cable", "intermediate"),
    ("Suitcase Deadlift", "Bavul Deadlift", 6, 16, ["Lower Back", "Quadriceps"], "dumbbell", "intermediate"),
    ("Side Bend (Dumbbell)", "Yan Eğilme (Dumbbell)", 6, 16, [], "dumbbell", "beginner"),
    ("Side Bend (Cable)", "Yan Eğilme (Kablo)", 6, 16, [], "cable", "beginner"),
    ("Landmine Rotation", "Landmine Dönüş", 6, 16, ["Abs"], "barbell", "intermediate"),
    ("Medicine Ball Rotational Throw", "Tıp Topu Dönüş Fırlatma", 6, 16, ["Abs"], "other", "intermediate"),
    # Lower back / stability
    ("Superman", "Süpermen", 6, 4, ["Glutes"], "bodyweight", "beginner"),
    ("Bird Dog", "Kuş Köpek", 6, 4, ["Glutes", "Abs"], "bodyweight", "beginner"),
    ("Stir the Pot", "Karıştır", 6, 15, ["Lower Back"], "other", "intermediate"),
    ("Plank with Shoulder Tap", "Omuz Dokunuşlu Tahta", 6, 15, ["Obliques"], "bodyweight", "intermediate"),
    ("Suitcase Carry", "Bavul Taşıma", 6, 16, ["Traps", "Lower Back"], "dumbbell", "beginner"),
    ("Turkish Get-Up", "Türk Kalkışı", 6, 15, ["Glutes", "Traps", "Triceps"], "other", "advanced"),
    ("Copenhagen Plank", "Kopenhag Tahtası", 6, 16, ["Abs"], "bodyweight", "advanced"),
    ("Band Pallof Press", "Bantlı Pallof Baskı", 6, 16, ["Abs"], "band", "intermediate"),
    ("Single-Leg Dead Bug", "Tek Bacak Ölü Böcek", 6, 15, ["Lower Back"], "bodyweight", "intermediate"),
    ("Bear Crawl", "Ayı Yürüyüşü", 6, 15, ["Triceps", "Front Delt"], "bodyweight", "intermediate"),
    ("Inchworm", "Tırtıl Yürüyüşü", 6, 15, ["Triceps", "Front Delt"], "bodyweight", "beginner"),
    ("Core Roll-Out (Barbell)", "Barbell Core Rollout", 6, 15, ["Lower Back"], "barbell", "advanced"),
    ("Hollow Rock", "İçi Boş Kayık", 6, 15, ["Hip Flexors"], "bodyweight", "intermediate"),
    ("Ab Slider", "Ab Slider", 6, 15, ["Lower Back"], "other", "intermediate"),
    ("Stability Ball Pike", "Denge Topu Pike", 6, 15, ["Front Delt"], "other", "intermediate"),
]


def seed(db):
    if db.query(ExerciseCategory).count() > 0:
        print("Exercise data already seeded. Skipping.")
        return

    for cat in CATEGORIES:
        db.add(ExerciseCategory(**cat))
    db.flush()

    for mg in MUSCLE_GROUPS:
        db.add(MuscleGroup(**mg))
    db.flush()

    for row in EXERCISES:
        name, name_tr, cat_id, muscle_id, secondary, equipment, difficulty = row
        import json as _json
        db.add(Exercise(
            name=name,
            name_tr=name_tr,
            category_id=cat_id,
            primary_muscle_id=muscle_id,
            secondary_muscles=_json.dumps(secondary, ensure_ascii=False),
            equipment=equipment,
            difficulty=difficulty,
        ))

    db.commit()
    print(f"Seeded {len(CATEGORIES)} categories, {len(MUSCLE_GROUPS)} muscle groups, {len(EXERCISES)} exercises.")


if __name__ == "__main__":
    db = SessionLocal()
    try:
        seed(db)
    finally:
        db.close()
